n = int(input("dê um numero "))

x1 = (n * 1) 
x2 = (n * 2)
x3 = (n * 3)
x4 = (n * 4)
x5 = (n * 5)
x6 = (n * 6)
x7 = (n * 7)
x8 = (n * 8)
x9 = (n * 9)
x10 = (n * 10)

print("{} x 1 = |{}".format(n, x1))
print("{} x 2 = |{}".format(n, x2))
print("{} x 3 = |{}".format(n, x3))
print("{} x 4 = |{}".format(n, x4))
print("{} x 5 = |{}".format(n, x5))
print("{} x 6 = |{}".format(n, x6))
print("{} x 7 = |{}".format(n, x7))
print("{} x 8 = |{}".format(n, x8))
print("{} x 9 = |{}".format(n, x9))
print("{} x 10 = |{}".format(n, x10))